title: INF-2200 fall 2025

description: > # this means to ignore newlines until "contact:"
  Computer Architecture at UiT.

contact:
  email: 
  name: 

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
