title: inf-2200 fall 2024

description: > # this means to ignore newlines until "contact:"
  Computer Architecture at UiT.

contact:
  email: vi.n.tran@uit.no
  name: Vi Tran

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
